// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxqTlXl0y8LFtr_FmssKTh5y8PY-DkoQw',
    appId: '1:490782963360:web:6840eba3a72a8a7a43fbc5',
    messagingSenderId: '490782963360',
    projectId: 'api-tutorial-9b4d1',
    authDomain: 'api-tutorial-9b4d1.firebaseapp.com',
    storageBucket: 'api-tutorial-9b4d1.firebasestorage.app',
    measurementId: 'G-P4VDFJ72GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn09avY8t_4L_xz9TDVNI6c43xMdJG3Sc',
    appId: '1:490782963360:android:c648f178766a343643fbc5',
    messagingSenderId: '490782963360',
    projectId: 'api-tutorial-9b4d1',
    storageBucket: 'api-tutorial-9b4d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANWUPBcAEkxcso2GP4_mp6tIaky7P-G6k',
    appId: '1:490782963360:ios:e1daaee0ac309d8f43fbc5',
    messagingSenderId: '490782963360',
    projectId: 'api-tutorial-9b4d1',
    storageBucket: 'api-tutorial-9b4d1.firebasestorage.app',
    iosBundleId: 'com.example.apiTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANWUPBcAEkxcso2GP4_mp6tIaky7P-G6k',
    appId: '1:490782963360:ios:e1daaee0ac309d8f43fbc5',
    messagingSenderId: '490782963360',
    projectId: 'api-tutorial-9b4d1',
    storageBucket: 'api-tutorial-9b4d1.firebasestorage.app',
    iosBundleId: 'com.example.apiTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxqTlXl0y8LFtr_FmssKTh5y8PY-DkoQw',
    appId: '1:490782963360:web:e6805052e497e3b143fbc5',
    messagingSenderId: '490782963360',
    projectId: 'api-tutorial-9b4d1',
    authDomain: 'api-tutorial-9b4d1.firebaseapp.com',
    storageBucket: 'api-tutorial-9b4d1.firebasestorage.app',
    measurementId: 'G-G47BWNL84B',
  );
}
